[tool.black]
line-length = 119
required-version = "22.3.0"

[tool.isort]
profile = "black"
line_length = 119
combine_as_imports = true
combine_star = true
known_local_folder = ["arguments", "test_utils", "tests", "utils"]

[tool.coverage.run]
concurrency = ["thread", "multiprocessing"]
omit = ["hivemind/proto/*"]
source = ["hivemind"]

[tool.ruff]
exclude = [
    "__init__.py",
    "*_pb2.py"
]
line-length = 119
required-version = "==0.5.1"
target-version = "py38"

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501", "E702"]
dummy-variable-rgx = "^_$"

[tool.ruff.lint.isort]
known-first-party = ["arguments", "test_utils", "tests", "utils"]
